version: 2
jobs:
  build:
    docker:
      # Primary
      - image: myriadeinc/node-ci:latest
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            npm install
      - run:
          name: Build using Webpack
          command: |
            npm run build
      - run:
          name: Login to Firebase CLI
          command: |
            do stuff
      - deploy:
          name: Deploying to myriade-web-staging
          command: |
            make deploy-staging
  # deloy_staging:
  #   docker:
  #     - image: myriadeinc/node-ci:latest
  #   steps:
  #     - checkout
  #     - run:
  #         name: Login to Firebase CLI
  #         command: |
  #           do stuff
  #     - run:
  #         name: Deploying to myriade-web-staging
  #         command: |
  #           make deploy-staging
# workflows:
#   version: 2
#   build_and_test:
#     jobs:
#       - build
#       - deploy_staging
#       - hold: 
#           type: approval
#           requires: build
#       - deploy:
#           name: Deploy build
#           command: |
#             firebase deploy