version: 2
jobs:
  build:
    docker:
      - image: myriadeinc/node-ci:latest
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: |
            npm install
      - run:
          name: Build using Webpack
          command: |
            make build
      - run:
          name: Deploying to myriade-web
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              make deploy-ci
            fi